version: "3"

services:
  geth:
    image: mrbrown6210/geth:1.0.0
    ports:
      - 3000:3000
    environment:
      - BACKEND_PORT=80
  server:
    image: mrbrown6210/geth-api:1.0.0
    ports:
      - 80:80
    links:
      - server-database:mongo
    depends_on:
      - server-database
    environment:
      - DATABASE_URL=server-database
      - PORT=80
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
